server:
    port: 8083
spring:
  application:
    name: likelion-websocket
  rabbitmq:
    username: admin
    password: abcde12# #default Password
    host: localhost # default host
    port: 5672      #default port
